name: CI

on: [push]

jobs:
  build:
    runs-on: linux
    container:
      image: nixorg/nix
      env:
        NIX_PATH: nixpkgs=channel:nixos-19.09

    steps:
    - uses: actions/checkout@v1
    - run: nix-build
